#!/bin/bash --login

#SBATCH -D .
#SBATCH -J R09b_cmb
#SBATCH -A nosofs
#SBATCH -p hercules
##SBATCH --qos=windfall!debug
##queues: 'windfall' max 450 nodes (no walltime limit but lower priority; for quick turn-around try <=8 hrs)
###80 cores/node (mem 512GB/node)
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --exclusive
#SBATCH -t 02:00:00  
#SBATCH -o myout_cmb
#SBATCH -e err2.cmb
#SBATCH --mail-user=felicio.cassalho@noaa.gov
#SBATCH --mail-type=all  #send email for start, end and fail

set -e
ulimit -s unlimited 

source /home/felicioc/modules_schism.hercules

/work2/noaa/nos-surge/felicioc/BeringSea/R09b/outputs/combine_hotstart7.exe -i 0000
